### ISSUE TITLE
Support "Command ⌘ " modifier.

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [ycnmhd/obsidian-lineage#16]
Hi! An apple user here.

The current shortcut settings only seem to support `ctrl`, `alt` and `shift`.

**Comment by ycnmhd** [comment]
I updated the plugin to use `cmd` key instead of `ctrl` on Mac, but I don't have a physical device to test it.
Could you please test it and report back if it works as expected?
To do so, download the attached `main.js` and move it to the plugin folder `lineage` replacing the existing `main.js` file , then disable the plugin and re-enable it.

[main.zip](https://github.com/ycnmhd/obsidian-lineage/files/15210696/main.zip)

**Comment by CoffeeDrinkRabbit** [comment]
The Command key works fine, ~~and found it strange in testing that the `alt` key doesn't work anymore.~~

~~Can't rule out that it's my system shortcuts taking over~~ (it is.), ~~so far I've tested all possible combinations with `alt` and none of them work. A possible solution would be to add `ctrl`, so that I can test and compare the effect of `ctrl+alt+key` with `command+alt+key` and `ctrl+command+alt+key`.~~

😜BTW, I would like to have both `ctrl` and `command` settings to avoid too many conflicting with system shortcuts.

**Comment by ycnmhd** [comment]
I updated the plugin so that
- `cmd` on Mac behaves like `ctrl` on Windows and Linux
- `ctrl` on Mac is an additional 4th modifier that is not available on Windows and Linux
Could you please test it (default and custom hotkeys) and report back if it works correctly?

[main.zip](https://github.com/ycnmhd/obsidian-lineage/files/15214772/main.zip)

**Comment by CoffeeDrinkRabbit** [comment]
Everything is running smoothly, thank you for your work!

**Comment by ycnmhd** [comment]
Thank you for testing it.
If any of the default hotkeys don't work because they conflict with macOS, I can replace the modifiers!
